name: Reusable workflow for ci pipeline

on:
  workflow_call:
    inputs:
      app-name:
        description: 'Name of the app'
        default: 'default config-path'
        required: true
        type: string
      app-type:
        description: 'Type of the app'
        default: 'default config-path'
        required: true
        type: string
    secrets:
      pat_token:
        description: 'PAT token passed from the caller workflow'
        required: false
      api-token:
        description: 'API token passed from the caller workflow'
        required: false

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - id: Check out repository
        uses: actions/checkout@v2
      - id: Print app-name and app-type
        run: echo "app-name is ${{ inputs.app-name }}, app-type is ${{ inputs.app-type }} "
      - id: Build and Push
        use: nhutpm219/.github/.github/composite-hello-world-steps@master