name: Reusable workflow example

on:
  workflow_call:
    inputs:
      the-parameters-1:
        required: true
        type: string
      the-parameters-2:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        param_1: ${{ inputs.the-parameters-1 }}
        param_2: ${{ inputs.the-parameters-2 }}

    - id: print_param_1
      run: echo "param 1 is ${{ inputs.the-parameters-1 }}"
    - id: print_param_2
      run: echo "param 2 is ${{ inputs.the-parameters-2 }}"
