name: Reusable workflow example 2

on:
  workflow_call:
    inputs:
      config-path:
        description: 'A config-path passed from the caller workflow'
        default: 'default config-path'
        required: false
        type: string
    secrets:
      pat_token:
        description: 'A token passed from the caller workflow'
        required: false
        default: ${{ secrets.WORKFLOW_AUTOMATION_TOKEN }}

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.WORKFLOW_AUTOMATION_TOKEN }}
        configuration-path: ${{ inputs.config-path }}
    - id: print_config_path
      run: echo "the config-path is ${{ inputs.config-path }}"